### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by Manoharvuradi** [saasfly/saasfly#68]
![image](https://github.com/saasfly/saasfly/assets/86292423/85eb2bce-dc9a-41cf-885a-a4712cd3dbcf)
After clicking Documentation Tab i got this error.

Module not found: Can't resolve '.contentlayer/generated'

**Comment by jackc3** [comment]
Have you run `bun run build` first? You can see this document: https://document.saasfly.io/get-started/installation/#run-build-first

<img width="780" alt="image" src="https://github.com/saasfly/saasfly/assets/10334353/18cf7e3b-e707-423a-b3ed-f78616227a43">

**Comment by Manoharvuradi** [comment]
Thanks, i was following Get Started Section

**Comment by Manoharvuradi** [comment]
Is there any active development currently underway?

**Comment by jackc3** [comment]
Yes, we will upgrade and release new features from time to time.
