### ISSUE TITLE
Email not sent (error 403 from resend), but nothing in log/server console

### ISSUE THREAD

**Issue by shuther** [saasfly/saasfly#90]
signup email was sent to resend but was rejected (I guess through POST call) due to lack of authentication that was expected. However, there was no error logged on the console. Is it expected? is there a way to report when this type of issue happens?

**Comment by jackc3** [comment]
You can see this question: https://discord.com/channels/1204690198382911488/1204986255453065226/threads/1252557658351997051

1. verify your domain on Resend
2. set resend  token
3. use cURL to test
4. check your pgsql config, keep right

**Comment by jackc3** [comment]
Thanks for your suggestion, we will add some logs later
