### ISSUE TITLE
Question: What are default.css inside styles/fonts/theme used for?

### ISSUE THREAD

**Issue by nicolagheza** [saasfly/saasfly#93]
Same as title.

**Comment by jackc3** [comment]
When we built these pages, we used different UI components. This might create different css files.

When you create new pages, you can delete these styles if you don't need them.

Thank you.

**Comment by nicolagheza** [comment]
> When we built these pages, we used different UI components. This might create different css files.
> 
> When you create new pages, you can delete these styles if you don't need them.
> 
> Thank you.

Thanks
