### ISSUE TITLE
DYNAMIC_SERVER_USAGE - some routes need dynamic serving

### ISSUE THREAD

**Issue by shuther** [saasfly/saasfly#98]
While running `bun run build ` I am getting few warnings referencing: https://nextjs.org/docs/messages/dynamic-server-error

- /zh/dashboard/billing 
- /ja/dashboard/billing
- /ko/dashboard/billing

What is strange is that there is nothing about the english version?
While the impact is likely small, it is something you may want to fix.

**Comment by jackc3** [comment]
Thanks @shuther , we will check and fix it.
